version: "3.8"
services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: ./node/Dockerfile
    ports:
      - 3000:5173
    volumes:
      - ./app:/app
      - /app/node_modules

  database:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: "my-bdd"
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080

  maildev:
    image: maildev/maildev
    container_name: maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"